version: 2
jobs:
  build:
    working_directory: ~/py-yacc
    docker:
      - image: circleci/python:2.7.15
        environment:
#          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python2.7/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "setup.py" }}
      - run:
          command: |
            sudo pip install -e .[test] -r requirements.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python2.7/site-packages"
      - run:
          command: |
            sudo pip install -e .
      - run:
          command: |
            nosetests --with-xcover --cover-html
      - store_test_results:
          path: cover
